import Head from 'next/head';
import Layout from '../components/Layout';
import Home from '../components/Home';

export default function Index() {
	return (
		<Layout>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="flex-1 h-screen w-full  pt-5 bg-green-100">
				<Home />
			</div>
		</Layout>
	);
}
